name: Lint Code Base

on:
  push:
    branches: [main]
  pull_request:
    branches-ignore:
      - "dependabot/**"

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CSS: false
          VALIDATE_CHECKOV: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN: false
